
export default {
	LEADER_BOARD: {
		SET_ALL: 'LEADER_BOARD_SET_ALL',
	},
	GAME: {
		START: 'GAME_START',
		SET_STATUS: 'GAME_SET_STATUS',
		RESET: 'GAME_SET_RESET',
		SET_SETTINGS: 'GAME_SET_SETTINGS',
		SET_ERROR: 'GAME_SET_ERROR'
	}
};
